POST http://{{host}}:{{port}}/project/user/add
Cookie: session={{session}}
Content-Type: application/json

{
    "id": "{{projectId}}",
    "user_id": "{{newProjectUserId}}",
    "role": "{{newProjectUserRole}}"
}