PATCH http://{{host}}:{{port}}/project/checklist/entry/check
Cookie: session={{session}}
Content-Type: application/json

{
  "projectId": "{{projectId}}",
  "versionNumber": "{{versionNumber}}",
  "entryId": "{{projectChecklistEntryId}}"
}