# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI BE

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Print User
      run: whoami

    - name: Transfer Secret to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: echo "${{ secrets.SETUP_ENV }}" > /home/Truncate/actions-runner/Truncate2023-Be/Truncate2023-BE/Truncate2023-BE/Truncate2023-BE/.env

    - name: Set Environment Variables
      run: echo "${{ secrets.SETUP_ENV }}" > .env

    - name: Install Dependencies
      run: npm i

    - name: Migrate Database
      run: npm run migrate

    - name: Pull db
      run: npx prisma db pull

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Build Nest.js Application
      run: npm run build

    - name: Restart Backend Api
      run: pm2 restart Truncate-Backend

