# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI BE

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm i

    - name: Set Environment Variables
      env:
        SETUP_ENV: ${{ secrets.SETUP_ENV }}
      run: echo "$SETUP_ENV" > .env

    - name: Migrate Database
      run: npm run migrate

    - name: Generate Prisma Client
      run: npx prisma db pull && npx prisma generate

    - name: Build Nest.js Application
      run: npm run build

    - name: Transfer Secret to Server
      run: scp -i ${{ secrets.SERVER_SSH_KEY }} .env ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/Truncate/actions-runner/Truncate2023-Be/Truncate2023-BE/Truncate2023-BE/Truncate2023-BE/

    - name: Restart Backend Api
      run: pm2 restart Truncate-Backend

